2015/app/templates/pages/faq.html

Merci de faire un check de l'orthographe

Adding the section about jury

---

2016/src/modules/bdxio/angular/components/home/SummaryContentComponent.ts

Found that small typo in the homepage.

Fix typo in the homepage

---

src/data/event.json
src/pages/index.tsx

Automatically display link on tickets selling opening.

Activate tickets link automatically

---

README.md

Add command to use the gatsby-cli that can be usefull for live reload

---

app/assets/styles/main.scss
app/components/homepage/SectionAbout.vue
app/components/layout/Header.vue
app/components/layout/grid/Flex-container.vue
app/components/layout/grid/Flex-item.vue
app/pages/index.vue

Resolves [#90](https://github.com/bdxio/bdxio.github.io/issues/90)
- Redesign `About us` section (responsive)
- Add line-height on texts
- Remove console.log

feat: redesign about us section

---

app/components/homepage/SectionAbout.vue
app/components/homepage/SectionThemes.vue
app/pages/index.vue

Fixes [#91](https://github.com/bdxio/bdxio.github.io/issues/91)

feat(themes): add themes section

---

app/components/homepage/SectionAbout.vue
app/components/homepage/SectionGuidage.vue
app/components/homepage/SectionThemes.vue
app/pages/index.vue

Fix `Guidage`, `Themes` and `About us` responsive issues

fix: responsiveness

---

app/assets/styles/main.scss
app/components/homepage/SectionHero.vue
app/components/layout/Header.vue
app/components/layout/IconBurger.vue

Repasse responsive pour les issues #107 et #87

:sparkles: responsive section hero + responsive menu display (hidden from now)

---

app/components/homepage/SectionAbout.vue
app/components/homepage/SectionNews.vue
app/components/homepage/SectionSpeaker.vue
app/components/homepage/SectionSponsor.vue
app/components/homepage/SectionSponsors.vue
app/components/homepage/SectionThemes.vue
app/pages/index.vue

Fixes #92 
Mobile | Desktop 
-- | --

feat(sponsor-speaker): add sections to homepage

---

app/components/homepage/SectionKeyConcepts.vue
app/components/homepage/SectionSpeaker.vue
app/components/homepage/SectionSponsor.vue
app/pages/index.vue

fix(key-concepts): responsive section

---

app/components/layout/TheNavigation.vue

feat: billetterie button

---

app/components/sponsors/SectionBecomeSponsor.vue

fix: center sponsors

---

api/config/database.js
api/src/api/sponsor-category/content-types/sponsor-category/schema.json
api/src/api/sponsor-category/controllers/sponsor-category.js
api/src/api/sponsor-category/routes/sponsor-category.js
api/src/api/sponsor-category/services/sponsor-category.js
api/src/api/sponsor/content-types/sponsor/schema.json
api/src/api/sponsor/controllers/sponsor.js
api/src/api/sponsor/routes/sponsor.js
api/src/api/sponsor/services/sponsor.js
app/.env.example

Create a `Sponsor` Table and a `Sponsor Category` Table
Sponsor 
- id 
- logo_url
- category liked to one `Sponsor Category`
Sponsor Category
- id
- name

chore(api): add Sponsors in Strapi

---

app/components/talk/TalkSectionPresentation.vue
app/components/talk/TalkSectionSpeaker.vue
app/nuxt.config.js
app/package.json
app/pages/talks/index.vue
app/yarn.lock

fix: add markdown support

---

app/pages/talks/index.vue

Autorise le ctrl + click (ou cmd + click) pour ouvrir les détails du talk dans une nouvelle tab.

fix: allow open talk details in new tab

---

app/components/layout/SectionGuidage.vue
app/pages/Schedule.vue

feat(schedule): add pdf program 

---

app/components/jobs/SectionJobs.vue
app/components/layout/TheNavigation.vue
app/pages/Jobs.vue

Docs https://docs.google.com/document/d/1AciroTIZF_KfP9S_bQ0g-h8prZqb1wtA0_jIsiOiyj4/edit?usp=sharing

feat(jobs): create page + welovedevs widget

---

api/config/database.js
api/config/env/production/database.js

- Added pool configuration to allow connection to database providers like Clever Cloud or whatever.
- Removed unused variable

chore: add knex config option to allow remote database connection

---

components/layout/header/Navigation.vue
components/link/Secondary.vue
components/section/homepage/Figures.vue
components/section/homepage/Speaker.vue
plugins/featureFlags.ts

MEP 24/05/2023

---

.nuxtignore
pages/Jobs.vue
plugins/featureFlags.ts

This reverts commit b3cf35db3e22430ee7fc8de0622245c64b98a789.

Revert "✨ display jobs page"

---

.nuxtignore
components/layout/Sponsors.vue
components/layout/header/index.vue
pages/Jobs.vue
plugins/featureFlags.ts

- revert jobs page
- set width / height for sponsors logos

MEP 05/07/2023

---

plugins/featureFlags.ts

à merger à partir du 20/07/2023

🚩 hide cfp link

---

.nuxtignore
pages/Schedule.vue
plugins/featureFlags.ts

MEP 06/09/2023

---

components/layout/Sponsors.vue
components/section/sponsors/Sponsors.vue
layouts/pageWithoutSponsors.vue
pages/Sponsors.vue

🎨 display balthazar sponsors in footer layout + all on specific sponsors page

---

components/layout/header/Navigation.vue
pages/Schedule.vue
plugins/featureFlags.ts

- display page speakers in menu if no schedule shown 
- hide talk page
- button to speakers list in schedule

🎨 Less links in menu 

---

package-lock.json
package.json
pages/FAQ.vue
pages/Schedule.vue

- faq params
- tailwind for schedule page

MEP 01/10/2023

---

components/layout/header/Navigation.vue
components/layout/header/index.vue
components/link/PrimaryButton.vue
package-lock.json
package.json
pages/FAQ.vue
pages/Schedule.vue

- fix faq page
- bdxio types 1.3.2
- improve accessibility

MEP 02/11/2023

---

pages/JeuConcours2023.vue
plugins/featureFlags.ts

MEP 03/11/2023

---

components/layout/header/Navigation.vue
components/section/association/Presentation.vue
components/section/association/Volunteers.vue
components/section/homepage/Categories.vue
components/section/homepage/Hero.vue
components/section/homepage/Sponsor.vue
components/section/jobs/index.vue
components/section/sponsors/BecomeSponsor.vue
components/section/sponsors/Offers.vue
components/section/talk/Category.vue
pages/FAQ.vue
pages/Schedule.vue
pages/Sponsors2022.vue
pages/talks/index.vue
plugins/featureFlags.ts

- hide billeterie
- fix css mobile schedule
- use css instead of postcss (not used anymore)

🎨 hide useless links + use css

---

components/section/sponsors/BecomeSponsor.vue
plugins/featureFlags/links/index.ts
plugins/featureFlags/sections/index.ts
utils/getNavigation.ts

Activation de l'offre sponsoring 2024

MEP 29/04/2024

---

plugins/featureFlags/links/index.ts
utils/getNavigation.ts

MEP 06/05/2024
